### PR TITLE
fix(loader): make sure loaded status is only set on loader hook

### LINKED ISSUE #77: (bug): `isLoaderLoaded()` is always true
_A very minor bug, but still wanted to document this :)_

**What happened**
I am trying to use `quibble` as a standalone pure ESM mock framework, even though this is mainly targeted at TestDoudble. While looking at usage in TD (https://github.com/testdouble/testdouble.js/blob/main/src/replace/index.js#L16), I see the check to see if the loader is actually activated. The function of `isLoaderLoaded`, however, always return true.

**What I expect**
When I do not use the quibble loader (`--loader/--experimental-loader quibble`) I expect the function of `isLoaderLoaded()` to return `false`.

**Playground**
https://stackblitz.com/edit/node-ej1hze?file=index.js&view=editor

---

It seems that `quibble.mjs`, and thus [the global quibble object identifie](https://github.com/testdouble/quibble/blob/main/lib/quibble.mjs#L9)r, is always loaded when importing the package (with and without loaders).

### PR DESCRIPTION
**Pull request by Nkmol**
Make sure the `isLoaded` state is explicitly set through the NodeJS loader life-cycle, instead of through global/implicit imports of the file. This makes sure the state is _only_ set when the file is loaded through a NodeJS loader.

To not worry about unloaded/loading states, I simply separated the loader tests (MJS and JS) through two different `teenytest` processes.

fixes #77

### CODE REVIEW

File: lib/quibble.mjs [hunk 1]
```diff
@@ -6,7 +6,9 @@ export const ignoreCallsFromThisFile = quibble.ignoreCallsFromThisFile
 export const config = quibble.config
 export const isLoaderLoaded = quibble.isLoaderLoaded
 
-global.__quibble = { stubModuleGeneration: 1 }
+export const globalPreload = () => {
```
Comment (giltayar) [inline lib/quibble.mjs:9]: This won't work in Node 14 because Node 14 uses a different function name [`getGlobalPreloadCode`](https://nodejs.org/docs/latest-v14.x/api/esm.html#esm_getglobalpreloadcode).

Also, while you're at it: these functions should be returning a `string`, and you're returning `undefined` here. In the interest of conforming to the spec, I suggest you return an empty string.

**Review by giltayar — CHANGES_REQUESTED** [review]

File: lib/quibble.mjs (hunk 1 above)
Comment (Nkmol) [reply lib/quibble.mjs]: Thanks for the review @giltayar! I have added the Node 14 hook, used normal function declaration to be in line with the other code, set the global state in user-land through the string (does not matter much where this happens I think).

**Comment by giltayar** [comment]
LGTM. Thanks!

**Comment by searls** [comment]
Landed in 0.6.15
